### ISSUE TITLE
Unable to Build project after importing Deque.AxeCore.Commons v4.7.2.0 from Nuget

### ISSUE THREAD

**Issue by YagoCP** [dequelabs/axe-core-nuget#105] opened 2023-08-31 13:08 UTC
Thank you for reporting an issue with one of our packages. Please provide all necessary information to reproduce the issue to assist with investigation

## Which package were you using when you encountered the issue?**
- [ ] Deque.AxeCore.Selenium
- [x] Deque.AxeCore.Playwright
- [x] Deque.AxeCore.Commons

## Describe the bug

We are unable to build the project after importing  `Deque.AxeCore.Commons` or `Deque.AxeCore.Playwright` due to issue on Nuget Package.

## How to reproduce

1. Import Package from Nugget
2. Build the Project
4. Build fails with Error: 
> CS8002  |  Referenced assembly 'Deque.AxeCore.Commons, Version=4.7.2.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
> CS8002  |  Referenced assembly 'Deque.AxeCore.Playwright, Version=4.7.2.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

## Screenshots

<img width="629" alt="image" src="https://github.com/dequelabs/axe-core-nuget/assets/118356003/0f983347-8965-44f9-b230-d4bd8668feab">

## Device Information
 - OS: Windows 11
 - Visual Studio Enterprise 2022 17.7.0
 - Deque.AxeCore.* Package Version(s) 4.7.2

**Comment by AdnoC** [comment] 2023-10-23 14:48
As a note to self: This is solved by signing our binaries.

**Comment by AdnoC** [comment] 2023-10-27 01:10
After some discussion, we have decided to close this issue without strongly naming our assemblies. As described in https://github.com/dequelabs/axe-core-nuget/pull/134#pullrequestreview-1695968154, suddenly making our assemblies strongly named would be a breaking change. As an alternative, we ask that you try to weakly name your test assembly or recompile this project yourself with a strong name (the work to strongly name is complete in the linked PR).

If anyone else has a requirement for strongly named assemblies please thumbs up the issue so we know that there is demand for it.

**Closed** 2023-10-27 01:10 UTC
Labels: bug, in sprint

**Comment by padmavemulapati** [comment] 2023-10-30 14:56
Not a bug

**Comment by SimonCropp** [comment] 2025-08-27 06:38
> . As an alternative, we ask that you try to weakly name your test assembly

note that this break the scenario where people want to use internalsvisibleto between their target project and their test project

**Comment by SimonCropp** [comment] 2025-08-27 06:39
IMO strong naming is flawed, but it has won. just bump the major and deploy a new version that is strong named
